name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'Token to get access to the private repo(s)'
  path:
    required: false
    description: 'The location of the json file where the yaml files are listed in order to merge it, if path was not provided, the value will point to the root folder of the repo'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
