name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'Token to get access to the private repo(s)'
    default: 'default value if applicable'
  inputPath:
    required: true
    description: 'The location of the json file where the yaml files are listed in order to merge it'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
